# Generated by Django 5.1.4 on 2025-01-11 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0005_order_payment_completed_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_completed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
    ]
