# Generated by Django 5.1.4 on 2025-01-11 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0007_productimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
